export const BOOKINGTYPECOLORS = {
    'TENTATIVE': '#e9c912',
    'CONFIRMED': '#e95d12',
    'CLEANING': '#ac12e9'
  }

export const CALENDAR_CLEANING = 'CLEANING'
export const CALENDAR_CONFIRMED = 'CONFIRMED'
export const CALENDAR_TENTATVE = 'TENTATIVE'
